INSERT INTO exercise (name, muscle_group, type) VALUES

 	 ('Flat Bench Press', 0, 0),
    ('Incline Bench Press', 0, 0),
    ('Flat Bench Dumbbell Press', 0, 0),
    ('Incline Bench Dumbbell Press', 0, 0),
    ('Flat Bench Dumbbell Fly', 0, 1),
    ('Incline Bench Dumbbell Fly', 0, 1),
    ('Standing Cable Press', 0, 0),
    ('Standing Cable Fly', 0, 1),

    ('Pull-up', 1, 0),
    ('Barbell Row', 1, 0),
    ('Dumbbell Row', 1, 0),
    ('Lat Pulldown', 1, 0),
    ('Seated Cable Row', 1, 0),
    ('Chest Supported Dumbbell Row', 1, 1),
    ('Deadlift', 1, 0),
    ('T-Bar Row', 1, 0),

    ('Back Squat', 2, 0),
    ('Front Squat', 2, 0),
    ('Lunges', 2, 0),
    ('Machine Leg Extension', 2, 1),
    ('Machine Leg Curl', 2, 1),
    ('Bulgarian Squat', 2, 0),
    ('Box Jumps', 2, 0),
    ('Sled Push', 2, 0),

    ('Military Press', 3, 0),
    ('Seated Dumbbell Shoulder Press', 3, 0),
    ('Lateral Dumbbell Rise', 3, 1),
    ('Front Dumbbell Rise', 3, 1),
    ('Reverse Fly', 3, 1),
    ('One Hand Cable Lateral Rise', 3, 1),

    ('Skullcrusher', 4, 0),
    ('Bent Over Dumbbell Triceps Extension', 4, 1),
    ('Dips', 4, 0),
    ('Cable Extension', 4, 1),
    ('Seated Overhead Dumbbell Extension', 4, 0),
    ('Bench Dips', 4, 0),

    ('Barbell Curl', 5, 0),
    ('Dumbbell Curl', 5, 0),
    ('Hammer Dumbbell Curl', 5, 0),
    ('Cable Curl', 5, 0),
    ('Preacher Curl', 5, 1),
    ('Concentrated Curl', 5, 1),

    ('Crunches', 6, 0),
    ('Leg Rises', 6, 0),
    ('Side To Side Crunches', 6, 0),
    ('Plank Hold', 6, 0),
    ('Toe Reach', 6, 0),
    ('V-Ups', 6, 0);